### PR TITLE
Improve coverage

### PR DESCRIPTION
**Pull request by paraynaud**

### CODE REVIEW

**Comment by paraynaud** [comment]
+5.23%

**Comment by paraynaud** [comment]
+6.48%

**Comment by paraynaud** [comment]
+8,73%

**Comment by paraynaud** [comment]
+9.67%

**Comment by paraynaud** [comment]
+9.67%

**Comment by paraynaud** [comment]
+12.07%

**Comment by paraynaud** [comment]
+14.08%

**Comment by paraynaud** [comment]
+15.13%

**Comment by paraynaud** [comment]
+16.28

**Comment by paraynaud** [comment]
17.47%

**Comment by paraynaud** [comment]
+18.15%

**Comment by paraynaud** [comment]
+18.76

**Comment by paraynaud** [comment]
+20.59%

**Comment by paraynaud** [comment]
@dpo, I will stop the coverage improvements for this pass.
I will improve it again later!
We are at 79% now (from 59%).

**Comment by paraynaud** [comment]
It is strange, I don't need an approved review to rebase-merge.

**Comment by dpo** [comment]
Thank you @paraynaud! Let's leave it for now.

**Pull request merged**
