### PR TITLE
`get_expression_tree` from models

### PR DESCRIPTION
**Pull request by paraynaud**
add get_expr_tree + test for MathOptNLPModel + JuMP.Model + ADNLPModel

#30

I worked on it to produce profiles.

### CODE REVIEW

**Comment by paraynaud** [comment]
Manifest.toml should be remove from the repository, I didn't remove it, to stay the PR orthogonal.

**Review by dpo — CHANGES_REQUESTED** [review]
Remove the Manifest, rebase and force-push.

**Comment by paraynaud** [comment]
> Remove the Manifest, rebase and force-push.

Should I:
- remove the Manifest in another branch rm-Manifest, merge-rebase it into master and finally rebase this branch to master?
- remove Manifest.toml in this branch?

**Comment by dpo** [comment]
```
git rm Manifest.toml
git commit --amend
git push -f
```

**Review by dpo — APPROVED** [review]
Thank you!

**Pull request merged**
